channels:
- conda-forge
dependencies:
- python=3.11.9
- pip<=24.1.2
- pip:
  - mlflow==2.14.1
  - astunparse==1.6.3
  - cloudpickle==2.2.1
  - dill==0.3.8
  - numpy==1.24.4
  - optree==0.11.0
  - packaging==24.1
  - pandas==1.5.3
  - psutil==6.0.0
  - pydot==1.4.2
  - pyyaml==6.0.1
  - scikit-learn==1.5.0
  - scipy==1.11.4
  - skorch==1.0.0
  - torch==2.3.1
  - wcwidth==0.2.13
name: mlflow-env
