model_name: model_1
module_name: src.model  # Add this line to specify the module
artifact_path: deep_model_1

tag_key: "model"
tag_value: "deep model 1"

params:
  learning_rate: [0.001, 0.05, 0.01]
  dropout_rate: [0.0, 0.2, 0.5]
  batch_size: [16, 32, 64]
  epochs: [20, 30]

folds: 5
random_state: 42
cv_n_jobs: 1
metrics:
  rmse: 'neg_root_mean_squared_error'
evaluation_metric: 'rmse'
