defaults:
  - _self_

folds: 3

# evaluation_metric: "f1"
# cv_evaluation_metric: "mean_test_f1"

# pyfunc_predict_fn: "predict_proba"

# metrics:
#   accuracy: "accuracy"
#   f1: "f1"

evaluation_metric: "neg_mean_squared_error"
cv_evaluation_metric: "mean_test_neg_mean_squared_error"

pyfunc_predict_fn: "predict"

metrics:
  r2: "r2"
  neg_mean_squared_error: "neg_mean_squared_error"
  neg_mean_absolute_error: "neg_mean_absolute_error"