model_name: random_forest
artifact_path: basic_rf

tag_key: "model"
tag_value: "basic RF"

module_name: "sklearn.linear_model"
class_name: "SGDRegressor"

params:
  # n_estimators: [100, 200, 500]
  # criterion: ['gini', 'entropy', 'log_loss']
  # random_state: [88] #, 100, 44]
  penalty: ['l1', 'l2']
  # solver: ["saga", "lbfgs", "liblinear"]
  max_iter: [2]
  random_state: [88] #, 100, 44]
  # C: [0.1, 0.5, 0.9]
