defaults:
  - _self_
  - logistic_regression  # Default to Logistic Regression

# Define your parameters here
data_version: v1
split_ratio:
  train: 0.8
  validation: 0.2
test_data_version: v2
test_split_ratio: 0.5
cv_folds: 3
